// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/google": {
            "post": {
                "description": "Verify Google ID Token and return JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with Google",
                "parameters": [
                    {
                        "description": "Google ID Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/otp": {
            "post": {
                "description": "Use for testing OTP rate limiter (1 request per minute)",
                "tags": [
                    "otp"
                ],
                "summary": "Test OTP endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.OTPResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/onboarding": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save company and user info (step before OTP)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User onboarding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Onboarding data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OnboardingPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.OnboardingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/test": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user_id from JWT",
                "tags": [
                    "user"
                ],
                "summary": "Get current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "OTP sent successfully"
                },
                "status": {
                    "description": "suc/fail/err",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "needOnboarding": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "handlers.OTPResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "alley": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sub_district": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.OnboardingPayload": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 ถนนสุขุมวิท"
                },
                "alley": {
                    "type": "string",
                    "example": "Soi 5"
                },
                "companyName": {
                    "type": "string",
                    "example": "ABC Co."
                },
                "companyType": {
                    "type": "string",
                    "example": "SME"
                },
                "district": {
                    "type": "string",
                    "example": "Pathum Wan"
                },
                "postalCode": {
                    "type": "string",
                    "example": "10330"
                },
                "province": {
                    "type": "string",
                    "example": "Bangkok"
                },
                "subDistrict": {
                    "type": "string",
                    "example": "Lumphini"
                },
                "tel": {
                    "type": "string",
                    "example": "0999999999"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "company": {
                    "$ref": "#/definitions/models.Company"
                },
                "companyID": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "google_id": {
                    "type": "string"
                },
                "is_validated": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "tel_otp": {
                    "type": "string"
                }
            }
        },
        "services.RequestOTPRequest": {
            "type": "object",
            "properties": {
                "tel": {
                    "type": "string",
                    "example": "0812345678"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "services.RequestOTPResponse": {
            "type": "object",
            "properties": {
                "refNo": {
                    "type": "string",
                    "example": "ABC123"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "services.VerifyOTPRequest": {
            "type": "object",
            "properties": {
                "pin": {
                    "type": "string",
                    "example": "123456"
                },
                "refNo": {
                    "type": "string",
                    "example": "ABC123"
                },
                "tel": {
                    "type": "string",
                    "example": "0812345678"
                }
            }
        },
        "services.VerifyOTPResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
