// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/google": {
            "post": {
                "description": "Verify Google ID Token and return JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with Google",
                "parameters": [
                    {
                        "description": "Google ID Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/otp": {
            "post": {
                "description": "Use for testing OTP rate limiter (1 request per minute)",
                "tags": [
                    "otp"
                ],
                "summary": "Test OTP endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.OTPResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matrix": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Build an n×n distance matrix from a list of lat/lng locations. Durations in minutes, distances in meters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "summary": "Build distance matrix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "List of locations (min 2)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatrixRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BuildMatrixResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/onboarding": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save company and user info (step before OTP)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "User onboarding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Onboarding data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OnboardingPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.OnboardingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/onboarding/otp": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send an OTP SMS to the given phone number. Requires a valid JWT. Returns a refNo to use during verification.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Request OTP",
                "parameters": [
                    {
                        "description": "Phone number payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.OTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RequestOTPResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Missing/invalid tel field or malformed body",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid JWT",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "409": {
                        "description": "Phone already verified / recent request exists / user exceeded request limit",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream OTP provider unavailable",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    }
                }
            }
        },
        "/api/onboarding/otp/verify": {
            "post": {
                "description": "Verify an OTP pin using the refNo and phone number from the request step. Increments attempt count on failure and marks the OTP as used on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "onboarding"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "OTP verification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verified; user phone validated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.OTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.VerifyOTPResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Missing/invalid tel, pin, or refNo — or record not found",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "401": {
                        "description": "Incorrect OTP pin",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "409": {
                        "description": "OTP expired / already used / max attempts reached",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.OTPResponse"
                        }
                    }
                }
            }
        },
        "/api/optimize": {
            "post": {
                "description": "Optimize vehicle routing problem given vehicles and orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "planning"
                ],
                "summary": "Optimize vehicle routing",
                "parameters": [
                    {
                        "description": "optimize request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OptimizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.OptimizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.OptimizeResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create multiple orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create order list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Order list",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupCreateOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete multiple orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Delete order list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Order IDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteVehicle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/orders/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Patch order by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Update order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/plan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Create plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/plan/:id": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "user has to be in the same company as target plan to allow duplicating it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "DuplicatePlan and its legacy by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DuplicatePlanByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DuplicatePlanByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "hard delete plan by id by attach plan id via url params, it will delte all its legacy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Delete plan by plan id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeletePlanByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeletePlanByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Patch a plan name by id by attach plan id via url params, and updated name by body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Patch plan name by plan id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "plan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePlanNameByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePlanNameByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/skills": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create multiple skills by plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skill"
                ],
                "summary": "Create skill list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Skill list",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupCreateTagSkill"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TagSkillGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/test": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user_id from JWT",
                "tags": [
                    "user"
                ],
                "summary": "Get current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/vehicles": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create multiple vehicles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "Create vehicle list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Vehicle list",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupCreateVehicle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.VehicleGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete multiple vehicles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "Delete vehicle list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Vehicle IDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteVehicle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/vehicles/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Patch vehicle by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "Update vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vehicle update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVehicle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.VehicleGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateOrder": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "des_latitude": {
                    "type": "number"
                },
                "des_longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "priority": {
                    "description": "0-3",
                    "type": "integer"
                },
                "service_time": {
                    "type": "integer"
                },
                "tag_skill_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "time_window_end": {
                    "type": "integer"
                },
                "time_window_start": {
                    "type": "integer"
                },
                "type": {
                    "description": "0=delivery,1=pickup",
                    "type": "integer"
                }
            }
        },
        "dto.CreatePlanRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "untangle"
                },
                "plan_date": {
                    "type": "string",
                    "example": "2026-05-05 15:44:09.523069+00"
                }
            }
        },
        "dto.CreatePlanResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-05-05 15:44:09.523069+00"
                },
                "id": {
                    "type": "string",
                    "example": "whatthehell"
                },
                "name": {
                    "type": "string",
                    "example": "what"
                }
            }
        },
        "dto.CreateTagSkill": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CreateVehicle": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "daily_break_time_end": {
                    "type": "integer"
                },
                "daily_break_time_start": {
                    "type": "integer"
                },
                "daily_work_time_end": {
                    "type": "integer"
                },
                "daily_work_time_start": {
                    "type": "integer"
                },
                "end_latitude": {
                    "type": "number"
                },
                "end_longitude": {
                    "type": "number"
                },
                "max_task": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "integer"
                },
                "start_latitude": {
                    "type": "number"
                },
                "start_longitude": {
                    "type": "number"
                },
                "tag_skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VehicleTagSkill"
                    }
                }
            }
        },
        "dto.DeletePlanByIDRequest": {
            "type": "object"
        },
        "dto.DeletePlanByIDResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "plan deleted"
                }
            }
        },
        "dto.DeleteVehicle": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "plan_id": {
                    "type": "string"
                }
            }
        },
        "dto.DuplicatePlanByIDRequest": {
            "type": "object"
        },
        "dto.DuplicatePlanByIDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "whatthehell"
                },
                "name": {
                    "type": "string",
                    "example": "vhkp9^,lvo0y[0bh'0dsojvp]"
                }
            }
        },
        "dto.GroupCreateOrder": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateOrder"
                    }
                },
                "plan_id": {
                    "type": "string"
                }
            }
        },
        "dto.GroupCreateTagSkill": {
            "type": "object",
            "properties": {
                "plan_id": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateTagSkill"
                    }
                }
            }
        },
        "dto.GroupCreateVehicle": {
            "type": "object",
            "properties": {
                "plan_id": {
                    "type": "string"
                },
                "vehicles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateVehicle"
                    }
                }
            }
        },
        "dto.LocationInput": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "dto.MatrixRequest": {
            "type": "object",
            "properties": {
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LocationInput"
                    }
                }
            }
        },
        "dto.OTPErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                }
            }
        },
        "dto.OTPResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/dto.OTPErrorInfo"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.OptimizeOrder": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "des_latitude": {
                    "type": "number"
                },
                "des_longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "service_time": {
                    "type": "integer"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateTagSkill"
                    }
                },
                "time_window_end": {
                    "type": "integer"
                },
                "time_window_start": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "dto.OptimizeRequest": {
            "type": "object",
            "required": [
                "depot_lat",
                "depot_lon",
                "orders",
                "vehicles"
            ],
            "properties": {
                "depot_lat": {
                    "type": "number"
                },
                "depot_lon": {
                    "type": "number"
                },
                "enable_alns": {
                    "type": "boolean"
                },
                "enable_multi_trip": {
                    "type": "boolean"
                },
                "orders": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.OptimizeOrder"
                    }
                },
                "reload_min": {
                    "description": "minutes; 0 = server default (30)",
                    "type": "integer"
                },
                "seed": {
                    "description": "0 = non-deterministic",
                    "type": "integer"
                },
                "time_limit_ms": {
                    "description": "0 = server default (5000)",
                    "type": "integer"
                },
                "vehicles": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.OptimizeVehicle"
                    }
                }
            }
        },
        "dto.OptimizeVehicle": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "daily_break_time_end": {
                    "type": "integer"
                },
                "daily_break_time_start": {
                    "type": "integer"
                },
                "daily_work_time_end": {
                    "type": "integer"
                },
                "daily_work_time_start": {
                    "type": "integer"
                },
                "end_latitude": {
                    "type": "number"
                },
                "end_longitude": {
                    "type": "number"
                },
                "max_task": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateTagSkill"
                    }
                },
                "start_latitude": {
                    "type": "number"
                },
                "start_longitude": {
                    "type": "number"
                }
            }
        },
        "dto.RequestOTPRequest": {
            "type": "object",
            "required": [
                "tel"
            ],
            "properties": {
                "tel": {
                    "type": "string",
                    "example": "0812345678"
                }
            }
        },
        "dto.RequestOTPResponse": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 0
                },
                "expires_at": {
                    "type": "string"
                },
                "max_attempts": {
                    "type": "integer",
                    "example": 5
                },
                "refNo": {
                    "type": "string",
                    "example": "ABC123"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "tel": {
                    "type": "string",
                    "example": "0999999999"
                }
            }
        },
        "dto.UpdateOrder": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "des_latitude": {
                    "type": "number"
                },
                "des_longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "service_time": {
                    "type": "integer"
                },
                "tag_skill_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "time_window_end": {
                    "type": "integer"
                },
                "time_window_start": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdatePlanNameByIDRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "united in grief"
                }
            }
        },
        "dto.UpdatePlanNameByIDResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "united in grief"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateVehicle": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "daily_break_time_end": {
                    "type": "integer"
                },
                "daily_break_time_start": {
                    "type": "integer"
                },
                "daily_work_time_end": {
                    "type": "integer"
                },
                "daily_work_time_start": {
                    "type": "integer"
                },
                "end_latitude": {
                    "type": "number"
                },
                "end_longitude": {
                    "type": "number"
                },
                "max_task": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "integer"
                },
                "start_latitude": {
                    "type": "number"
                },
                "start_longitude": {
                    "type": "number"
                },
                "tag_skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VehicleTagSkill"
                    }
                }
            }
        },
        "dto.VehicleTagSkill": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "pin",
                "refNo",
                "tel"
            ],
            "properties": {
                "pin": {
                    "type": "string",
                    "example": "123456"
                },
                "refNo": {
                    "type": "string",
                    "example": "ABC123"
                },
                "tel": {
                    "type": "string",
                    "example": "0812345678"
                }
            }
        },
        "dto.VerifyOTPResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "handlers.CreateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "needOnboarding": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "handlers.OTPResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.OnboardingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sub_district": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.OnboardingPayload": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "123 ถนนสุขุมวิท"
                },
                "companyName": {
                    "type": "string",
                    "example": "ABC Co."
                },
                "companyType": {
                    "type": "string",
                    "example": "SME"
                },
                "district": {
                    "type": "string",
                    "example": "Pathum Wan"
                },
                "postalCode": {
                    "type": "string",
                    "example": "10330"
                },
                "province": {
                    "type": "string",
                    "example": "Bangkok"
                },
                "subDistrict": {
                    "type": "string",
                    "example": "Lumphini"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "company": {
                    "$ref": "#/definitions/models.Company"
                },
                "companyID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "google_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_need_on_boarding": {
                    "type": "boolean"
                },
                "is_validated": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "response.BuildMatrixResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "node": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/response.MatrixResponse"
                }
            }
        },
        "response.DropReasonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "order_name": {
                    "type": "string"
                }
            }
        },
        "response.MatrixResponse": {
            "type": "object",
            "properties": {
                "distances": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "durations": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "response.OptimizeResponse": {
            "type": "object",
            "properties": {
                "drop_reasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.DropReasonResponse"
                    }
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RouteResponse"
                    }
                },
                "status": {
                    "type": "string"
                },
                "unassigned": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.OrderResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "priority": {
                    "description": "0-3",
                    "type": "integer"
                },
                "service_time": {
                    "type": "integer"
                },
                "tag_skill_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "type": {
                    "description": "0=delivery,1=pickup",
                    "type": "integer"
                }
            }
        },
        "response.RouteResponse": {
            "type": "object",
            "properties": {
                "stops": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.StopResponse"
                    }
                },
                "total_distance": {
                    "type": "number"
                },
                "total_duration": {
                    "type": "number"
                },
                "trip_sizes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "vehicle_name": {
                    "type": "string"
                }
            }
        },
        "response.StopResponse": {
            "type": "object",
            "properties": {
                "arrival_min": {
                    "type": "integer"
                },
                "depart_min": {
                    "type": "integer"
                },
                "order_name": {
                    "type": "string"
                }
            }
        },
        "response.TagSkillGroupResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TagSkillResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.TagSkillResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "order_count": {
                    "type": "integer"
                },
                "vehicle_count": {
                    "type": "integer"
                }
            }
        },
        "response.VehicleGroupResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.VehicleResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.VehicleResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "number"
                },
                "max_task": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plate_number": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "integer"
                },
                "tag_skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TagSkillResponse"
                    }
                },
                "vehicle_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
