definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  handlers.OTPResponse:
    properties:
      message:
        type: string
    type: object
  handlers.UserResponse:
    properties:
      email:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      google_id:
        type: string
      id:
        type: integer
      name:
        type: string
      pictures:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/google:
    post:
      consumes:
      - application/json
      description: Verify Google ID Token and return JWT
      parameters:
      - description: Google ID Token
        in: body
        name: body
        required: true
        schema:
          properties:
            id_token:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Login with Google
      tags:
      - auth
  /api/auth/otp:
    post:
      description: Use for testing OTP rate limiter (1 request per minute)
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.OTPResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Test OTP endpoint
      tags:
      - otp
  /api/test:
    get:
      description: Get user_id from JWT
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - user
swagger: "2.0"
